apiVersion: v1
kind: Deployment
metdata:
  name: filebeat-test
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: filebeat-test
    spec:
      containers:
      - name: filebeat
        image: filebeat
        volumeMounts:
        - name: filebeat-config
          mountPath: /etc/filebeat
        - name: weblog
          mountPath: /weblog
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: weblog
          mountPath: /var/log/nginx
      volumes:
      - name: weblog
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
---
apiVersion: v1
kind: service
metadata:
  name: filebeat-test
  labels:
    k8s-app: filebeat-test
spec:
  selector:
    k8s-app: filebeat-test
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30012
  type: NodePort 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yaml: |
    filebeat.prospectors:
    - input_type: log
      paths:
      - "/weblog/*"
    output.elasticsearch:
      hosts: ["192.168.23.204:9200"]
    username: "elastic"
    password: "pass"
    index: "filebeat-test"
