apiVersion: v1
kind: Pod
metadata:
  name: test-web
  labels:
    project: tj
  namespace: default
spec:
  containers:
  - name: test-web
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /var/log/nginx
      name: web-logpath
  volumes:
  - name: web-logpath
    emptyDir: {}  
