apiVersion: v1
kind: persistentVolume
metadata:
  name: data
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  emptyDir: {}
---
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: data
  namespace: defualt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "data"
