apiVersion: v1
kind: Pod
metadata:
  name: test-pvc
  labels:
    project: tj
  namespace: default
spec:
  containers:
  - name: test-pvc
    image: busybox
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - echo "test pvc nfs" >/test/test.txt
    volumeMounts:
    - mountPath: /test
      name: shared-volume
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: pvc-nfs
