apiVersion: v1
kind: Pod
metadata:
  name: web-pvc
  labels:
    project: tj
  namespace: default
spec:
  containers:
  - name: web-pvc
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /var/log/nginx
      name: web-logpath
  volumes:
  - name: web-logpath
    persistentVolumeClaim:
      claimName: pvc-nfs
