apiVersion: v1
kind: Pod
metadata:
  name: healthcheck-default
  labels:
    test: healthcheck-default
spec:
  restartPolicy: OnFailure
  containers:
  - name: healthcheck
    images: busybox
    args:
    - /bin/sh
    - -c
    - sleep 10; exit
    imagePullPolicy: IfNotPresent

