apiVersion: v1
kind: Pod
metadata:
  name: pod-usesecret
  labels:
    run: pod-usesecret
spec:
  containers:
  - name: pod-usesecret
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: db-password
