apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    run: backend
spec:
  containers:
  - name: backend
    image: nginx
    imagePullPolicy: IfNotPresent
    envFrom:
      - configMapRef:
          name: db-config
 

   
